// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetPosthogKeyData, GetPosthogKeyResponses, GetRedisStatusData, GetRedisStatusResponses, GetTrainDetailsData, GetTrainDetailsErrors, GetTrainDetailsResponses, GetTrainsData, GetTrainsResponses, RootData, RootResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 */
export const root = <ThrowOnError extends boolean = false>(options?: Options<RootData, ThrowOnError>) => {
    return (options?.client ?? client).get<RootResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/',
        ...options
    });
};

/**
 * Get Redis Status
 *
 * Get Redis connection status and test operations
 */
export const getRedisStatus = <ThrowOnError extends boolean = false>(options?: Options<GetRedisStatusData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetRedisStatusResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/redis',
        ...options
    });
};

/**
 * Get Trains
 *
 * Get trains information as GeoJSON FeatureCollection
 */
export const getTrains = <ThrowOnError extends boolean = false>(options?: Options<GetTrainsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTrainsResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/trains',
        ...options
    });
};

/**
 * Get Train Details
 *
 * Get specific train details
 */
export const getTrainDetails = <ThrowOnError extends boolean = false>(options: Options<GetTrainDetailsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTrainDetailsResponses, GetTrainDetailsErrors, ThrowOnError>({
        responseType: 'json',
        url: '/v1/trains/{vehicle_id}',
        ...options
    });
};

/**
 * Get Posthog Key
 *
 * Get Posthog key
 */
export const getPosthogKey = <ThrowOnError extends boolean = false>(options?: Options<GetPosthogKeyData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPosthogKeyResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/posthog',
        ...options
    });
};
