// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * APIResponse
 *
 * Main API response
 */
export type ApiResponse = {
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Nodatareceived
     */
    noDataReceived?: boolean | null;
    /**
     * Dataageminutes
     */
    dataAgeMinutes?: number | null;
    /**
     * Locations
     */
    locations: Array<VehiclePositionWithDelay>;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * Alert
 *
 * Alert information
 */
export type Alert = {
    /**
     * Alertdescriptiontext
     */
    alertDescriptionText: string;
    /**
     * Alerturl
     */
    alertUrl?: string | null;
    /**
     * Effectivestartdate
     */
    effectiveStartDate: number;
    /**
     * Effectiveenddate
     */
    effectiveEndDate: number;
};

/**
 * InfoService
 *
 * Information service details
 */
export type InfoService = {
    /**
     * Name
     */
    name: string;
    /**
     * Fromstopindex
     */
    fromStopIndex: number;
    /**
     * Tillstopindex
     */
    tillStopIndex: number;
    /**
     * Fontcharset
     */
    fontCharSet: string;
    /**
     * Fontcode
     */
    fontCode: number;
    /**
     * Displayable
     */
    displayable: boolean;
};

/**
 * ProcessedStop
 *
 * Processed stop with distance information
 */
export type ProcessedStop = {
    /**
     * Id
     */
    id: string;
    /**
     * Originalcoords
     */
    originalCoords: Array<number>;
    /**
     * Distancealongroute
     */
    distanceAlongRoute: number;
    stopTimeInfo?: StopTimeWithCounty | null;
};

/**
 * Route
 *
 * Route information
 */
export type Route = {
    /**
     * Textcolor
     */
    textColor: string;
    /**
     * Shortname
     */
    shortName: string;
    /**
     * Longname
     */
    longName: string;
};

/**
 * StopTimeWithCounty
 *
 * Stop time information with county data
 */
export type StopTimeWithCounty = {
    /**
     * Scheduledarrival
     */
    scheduledArrival: number;
    /**
     * Realtimearrival
     */
    realtimeArrival: number;
    /**
     * Scheduleddeparture
     */
    scheduledDeparture: number;
    /**
     * Realtimedeparture
     */
    realtimeDeparture: number;
    stop: StopWithCounty;
};

/**
 * StopWithCounty
 *
 * Stop information with county data
 */
export type StopWithCounty = {
    /**
     * Name
     */
    name: string;
    /**
     * Lat
     */
    lat: number;
    /**
     * Lon
     */
    lon: number;
    /**
     * Platformcode
     */
    platformCode?: string | null;
    /**
     * County
     */
    county?: string | null;
};

/**
 * Trip
 *
 * Trip information
 */
export type Trip = {
    /**
     * Servicedate
     */
    serviceDate: string;
    /**
     * Tripshortname
     */
    tripShortName: string;
    route: Route;
    tripGeometry: TripGeometry;
    /**
     * Stoptimes
     */
    stoptimes: Array<StopTimeWithCounty>;
    /**
     * Wheelchairaccessible
     */
    wheelchairAccessible: string;
    /**
     * Bikesallowed
     */
    bikesAllowed: string;
    /**
     * Infoservices
     */
    infoServices: Array<InfoService>;
    /**
     * Alerts
     */
    alerts: Array<Alert>;
};

/**
 * TripGeometry
 *
 * Trip geometry polyline
 */
export type TripGeometry = {
    /**
     * Points
     */
    points: string;
};

/**
 * VehiclePositionWithDelay
 *
 * Complete vehicle position with delay and processing data
 */
export type VehiclePositionWithDelay = {
    /**
     * Vehicleid
     */
    vehicleId: string;
    /**
     * Lat
     */
    lat: number;
    /**
     * Lon
     */
    lon: number;
    /**
     * Heading
     */
    heading: number;
    /**
     * Speed
     */
    speed: number;
    /**
     * Lastupdated
     */
    lastUpdated: number;
    trip: Trip;
    /**
     * Delay
     */
    delay: number;
    /**
     * Trainposition
     */
    trainPosition: number;
    /**
     * Totalroutedistance
     */
    totalRouteDistance: number;
    /**
     * Processedstops
     */
    processedStops: Array<ProcessedStop>;
    vehicleProgress: VehicleProgress;
};

/**
 * VehicleProgress
 *
 * Vehicle progress between stops
 */
export type VehicleProgress = {
    /**
     * Laststop
     */
    lastStop: string;
    /**
     * Nextstop
     */
    nextStop: string;
    /**
     * Progress
     */
    progress: number;
};

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRedisStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/redis';
};

export type GetRedisStatusResponses = {
    /**
     * Response Getredisstatus
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetRedisStatusResponse = GetRedisStatusResponses[keyof GetRedisStatusResponses];

export type GetTrainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/trains';
};

export type GetTrainsResponses = {
    /**
     * Successful Response
     */
    200: ApiResponse;
};

export type GetTrainsResponse = GetTrainsResponses[keyof GetTrainsResponses];
