// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Alert
 *
 * Alert information
 */
export const zAlert = z.object({
    alertDescriptionText: z.string(),
    alertUrl: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    effectiveStartDate: z.int(),
    effectiveEndDate: z.int()
});

/**
 * InfoService
 *
 * Information service details
 */
export const zInfoService = z.object({
    name: z.string(),
    fromStopIndex: z.int(),
    tillStopIndex: z.int(),
    fontCharSet: z.string(),
    fontCode: z.int(),
    displayable: z.boolean()
});

/**
 * PosthogKey
 */
export const zPosthogKey = z.object({
    key: z.union([
        z.string(),
        z.null()
    ])
});

/**
 * Route
 *
 * Route information
 */
export const zRoute = z.object({
    textColor: z.string(),
    shortName: z.string(),
    longName: z.string()
});

/**
 * StopWithCounty
 *
 * Stop information with county data
 */
export const zStopWithCounty = z.object({
    name: z.string(),
    lat: z.number(),
    lon: z.number(),
    platformCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    county: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * StopTimeWithCounty
 *
 * Stop time information with county data
 */
export const zStopTimeWithCounty = z.object({
    scheduledArrival: z.int(),
    realtimeArrival: z.int(),
    scheduledDeparture: z.int(),
    realtimeDeparture: z.int(),
    stop: zStopWithCounty
});

/**
 * ProcessedStop
 *
 * Processed stop with distance information
 */
export const zProcessedStop = z.object({
    id: z.string(),
    originalCoords: z.array(z.number()),
    distanceAlongRoute: z.number(),
    stopTimeInfo: z.optional(z.union([
        zStopTimeWithCounty,
        z.null()
    ]))
});

/**
 * TripGeometry
 *
 * Trip geometry polyline
 */
export const zTripGeometry = z.object({
    points: z.string()
});

/**
 * Trip
 *
 * Trip information
 */
export const zTrip = z.object({
    serviceDate: z.string(),
    tripShortName: z.string(),
    route: zRoute,
    tripGeometry: zTripGeometry,
    stoptimes: z.array(zStopTimeWithCounty),
    wheelchairAccessible: z.string(),
    bikesAllowed: z.string(),
    infoServices: z.array(zInfoService),
    alerts: z.array(zAlert)
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([
        z.string(),
        z.int()
    ])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

/**
 * VehicleProgress
 *
 * Vehicle progress between stops
 */
export const zVehicleProgress = z.object({
    lastStop: z.string(),
    nextStop: z.string(),
    progress: z.number()
});

/**
 * TrainFeatureProperties
 *
 * Properties for a train feature (lighter version)
 */
export const zTrainFeatureProperties = z.object({
    vehicleId: z.string(),
    lat: z.number(),
    lon: z.number(),
    heading: z.number(),
    speed: z.number(),
    lastUpdated: z.int(),
    tripShortName: z.string(),
    delay: z.int(),
    trainPosition: z.number(),
    vehicleProgress: zVehicleProgress
});

/**
 * TrainFeature
 *
 * GeoJSON Feature for a train
 */
export const zTrainFeature = z.object({
    type: z.optional(z.string()).default('Feature'),
    geometry: z.record(z.string(), z.unknown()),
    properties: zTrainFeatureProperties
});

/**
 * TrainFeatureCollection
 *
 * GeoJSON FeatureCollection for trains
 */
export const zTrainFeatureCollection = z.object({
    type: z.optional(z.string()).default('FeatureCollection'),
    timestamp: z.string(),
    noDataReceived: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    dataAgeMinutes: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    features: z.array(zTrainFeature)
});

/**
 * VehiclePositionWithDelay
 *
 * Complete vehicle position with delay and processing data
 */
export const zVehiclePositionWithDelay = z.object({
    vehicleId: z.string(),
    lat: z.number(),
    lon: z.number(),
    heading: z.number(),
    speed: z.number(),
    lastUpdated: z.int(),
    trip: zTrip,
    delay: z.int(),
    trainPosition: z.number(),
    totalRouteDistance: z.number(),
    processedStops: z.array(zProcessedStop),
    vehicleProgress: zVehicleProgress
});

export const zRootData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetRedisStatusData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Getredisstatus
 *
 * Successful Response
 */
export const zGetRedisStatusResponse = z.record(z.string(), z.string());

export const zGetTrainsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetTrainsResponse = zTrainFeatureCollection;

export const zGetTrainDetailsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        vehicle_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetTrainDetailsResponse = zVehiclePositionWithDelay;

export const zGetPosthogKeyData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetPosthogKeyResponse = zPosthogKey;
