// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getRedisStatus, getTrains, home, type Options } from '../sdk.gen';
import type { GetRedisStatusData, GetTrainsData, HomeData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getRedisStatusQueryKey = (options?: Options<GetRedisStatusData>) => createQueryKey('getRedisStatus', options);

/**
 * Get Redis Status
 *
 * Get Redis connection status and test operations
 */
export const getRedisStatusOptions = (options?: Options<GetRedisStatusData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRedisStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRedisStatusQueryKey(options)
    });
};

export const getTrainsQueryKey = (options?: Options<GetTrainsData>) => createQueryKey('getTrains', options);

/**
 * Get Trains
 *
 * Get trains information
 */
export const getTrainsOptions = (options?: Options<GetTrainsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTrains({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getTrainsQueryKey(options)
    });
};

export const homeQueryKey = (options?: Options<HomeData>) => createQueryKey('home', options);

/**
 * Home
 */
export const homeOptions = (options?: Options<HomeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await home({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: homeQueryKey(options)
    });
};
